baseurl         = "/"
title           = "Colin McLear"
theme           = "bootstrap-premium"
paginate        = 10
copyright       = "Colin McLear"
DisqusShortname = "colinmclear"
enableRobotsTXT = true
# Google Analytics.
googleAnalytics = "UA-30497236-1"

[permalinks]
  post = "/:year/:title/"

[taxonomies]
tag = "tags"

[author]
  name = ""

[params]
hello = ""
description = ""

paginate_sections = 20
switchlang = false
BrandImage = ""
footline = "Powered by [Hugo](http://gohugo.io/) with a customized [bootstrap-premium](https://github.com/appernetic/hugo-bootstrap-premium/) theme Â· Hosted by [Netlify](https://netlify.com)"
mailmunchid = ""
sumomeid = ""
mathjax = ""
customCSS = [ "/css/custom.css" ]

showRightSidebar = true
# Sidebar social links.
github = "mclearc" # Your Github profile ID
twitter = "mclearc" # Your Twitter profile ID
philpeople = "colin-mclear"
university = "https://www.unl.edu/philosophy/"
department = "UNL Philosophy"

[params.theme]
# bootswatch theme name, select one: cerulean, cosmo, cyborg, darkly,
  # default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
  # slate, spacelab, superhero, united, yeti.
name = "cosmo"  # default, flatly, united, cosmo
inverse = "navbar-default"  # choose between navbar-inverse and navbar-default

[menu]
  [[menu.main]]
  identifier = "post"
  name       = "Blog"
  url        = "/posts/"


  [[menu.main]]
  identifier = "rss"
  name       = "RSS"
  url        = "/posts/index.xml"
