baseURL = 'https://www.colinmclear.net/'
title = 'Colin McLear'
theme = 'PaperMod'
enableRobotsTXT = true

[pagination]
pagerSize = 10
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

# Copyright notice
copyright = 'Colin McLear'

# Google Analytics
googleAnalytics = 'UA-30497236-1'

[minify]
disableXML = true

[permalinks]
posts = '/:year/:title/'

[taxonomies]
tag = 'tags'

[params]
env = 'production'
description = 'Colin McLear - Philosophy, Research, and Teaching'
author = 'Colin McLear'
defaultTheme = 'auto'
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = false
ShowWordCount = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = true
hideSummary = false
showtoc = false
tocopen = false

# Enable KaTeX for math rendering
[params.math]
enable = true

# Custom CSS
[[params.assets.css]]
href = '/css/custom.css'

# Profile/Home page mode
[params.profileMode]
enabled = true
title = 'Welcome!'
subtitle = '''
This site collects my research, teaching, and occasional blog posts on the history of modern philosophy and the philosophy of mind. My philosophical work focuses primarily on Kant and related figures in early modern philosophy and German Idealism, especially questions about perception, cognition, and self-knowledge.
<br><br>
I was previously Associate Professor of Philosophy at the University of Nebraska-Lincoln. Since leaving UNL in 2025 I continue to work in these areas as an independent scholar. <br><br>
My complete CV is available as <a href="/materials/McLearCV.pdf">PDF</a> or <a href="/materials/McLearCV.html">HTML</a>.
'''
imageUrl = ''
imageTitle = ''
imageWidth = 120
imageHeight = 120


# Social icons
[[params.socialIcons]]
name = 'email'
url = 'mailto:mclear@fastmail.com'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/mclearc'

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/mclearc'

[[params.socialIcons]]
name = 'mastodon'
url = 'https://fosstodon.org/@mclearc'

[[params.socialIcons]]
name = 'rss'
url = '/posts/index.xml'

# Main menu
[[menu.main]]
identifier = 'research'
name = 'Research'
url = '/research/'
weight = 10

[[menu.main]]
identifier = 'teaching'
name = 'Teaching'
url = '/teaching/'
weight = 20

[[menu.main]]
identifier = 'posts'
name = 'Blog'
url = '/posts/'
weight = 30

[[menu.main]]
identifier = 'resources'
name = 'Resources'
url = '/resources/'
weight = 40

[[menu.main]]
identifier = 'contact'
name = 'Contact'
url = '/contact/'
weight = 50

# Markup settings
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineNos = false
noClasses = false
style = 'monokai'

# Output formats
[outputs]
home = ['HTML', 'RSS', 'JSON']

# Privacy settings
[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = true
