[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.146.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --buildDrafts"

[context.deploy-preview.environment]
HUGO_VERSION = "0.146.0"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.146.0"

# Redirects from old Netlify URL to custom domain
[[redirects]]
  from = "https://brave-bassi-fae73b.netlify.com/*"
  to = "https://www.colinmclear.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://brave-bassi-fae73b.netlify.com/*"
  to = "https://www.colinmclear.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.brave-bassi-fae73b.netlify.com/*"
  to = "https://www.colinmclear.net/:splat"
  status = 301
  force = true
