[build]
publish = "public"
command = "hugo -F"

[context.production.environment]
HUGO_VERSION = "0.44"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts"

[context.deploy-preview.environment]
HUGO_VERSION = "0.44"

[[redirects]]
  from = "https://brave-bassi-fae73b.netlify.com/*"
  to = "https://www.colinmclear.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://brave-bassi-fae73b.netlify.com/*"
  to = "http://www.colinmclear.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.brave-bassi-fae73b.netlify.com/*"
  to = "https://www.colinmclear.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://brave-bassi-fae73b.netlify.com/*"
  to = "http://www.colinmclear.net/:splat"
  status = 301
  force = true
